- name: Base config for master + nodes
  hosts: master nodes

  tasks:

      - local_action: file path=../files/node_token state=absent

      - name: Download k3s
        get_url:
          url: https://get.k3s.io 
          dest: /home/ubuntu/installk3s.sh
          mode: '0700'

      - name: Copy new cmdline.txt file over
        copy:
          src: .../files/cmdline.txt
          dest: /boot/firmware/cmdline.txt
          follow: yes

- name: Install k3s on master node
  hosts: master

  tasks:

      - name: Install k3s
        command: "/home/ubuntu/installk3s.sh --disable servicelb --no-deploy traefik"
        become: yes

      - name: Load data
        slurp:
          src: /var/lib/rancher/k3s/server/node-token
        register: slurped_user_data
        become: yes

      - name: Decode data and store as fact
        set_fact:
          slurped_node_token: "{{ slurped_user_data.content | b64decode}}"

      - local_action: copy content={{ slurped_node_token }} dest=../files/node_token

- name: Install k3s on worker nodes
  hosts: nodes

  tasks:

      - name: Read node token from file
        set_fact:
          node_token: "{{lookup('file', '../files/node_token') }}"

      - name: Ansible Template Example
        template:
          src: k3s-agent.sh
          dest: /home/ubuntu/k3s-agent.sh
          mode: 0777

      - name: Install k3s on nodes
        command: "/home/ubuntu/k3s-agent.sh --disable servicelb --no-deploy traefik"
        become: yes

- name: Install k3s on jetson node(s)
  hosts: jetson

  tasks:

      - name: Download k3s
        get_url:
          url: https://get.k3s.io 
          dest: /home/jetson/installk3s.sh
          mode: '0700'

      - name: Read node token from file
        set_fact:
          node_token: "{{lookup('file', '../files/node_token') }}"

      - name: Ansible Template Example
        template:
          src: k3s-agent.sh
          dest: /home/jetson/k3s-agent.sh
          mode: 0777

      - name: Install k3s on nodes
        command: "/home/jetson/k3s-agent.sh --disable servicelb --no-deploy traefik"
        become: yes